### ISSUE TITLE
[Bug] Cannot target certain components by name

### ISSUE THREAD

**Issue by alhankeser** [VariateApp/variate-vue#4]
## Description
For some reason, when I target my component `features` (also tried `Features`) I cannot get the variation attributes to be passed to the component in question. 

## How To Reproduce
1. Config: https://github.com/alhankeser/variate-vue-demo-issues/blob/bug/target-component/variate.json#L117
2. Features.vue: https://github.com/alhankeser/variate-vue-demo-issues/blob/bug/target-component/src/views/Features.vue#L59
3. Navigate to /features and the default headline will always show even though I have qualified into a variation. 

## Expected behavior
I expected to see one of my variation headlines instead of the default headline. 

### Desktop (please complete the following information):**
 - OS: macOS 10.14.5
 - Browser: Chrome
 - Version: 78.0.3904.97

**Comment by foxted** [comment]
There is a fix for this: you can use the `variateId` prop on your page components (components directly connected to Vue Router).

To do so, declare your route as usual in the `router.js` file, but add a prop `variateId` to your route with the name that you want to give your component, for example: 

```javascript
const router = new Router({
    mode: 'history',
    routes: [
        {
            path: '/',
            name: 'Home',
            component: Home,
            props: {
                variateId: 'Home'
            }
        }
    ]
});
```

We should remember to document this in the documentation.

cc. @alhankeser

**Comment by alhankeser** [comment]
Works as expected! Added to backlog for Documentation https://github.com/orgs/VariateApp/projects/1#card-30037417
